### ISSUE TITLE
QC: Update Contributor Guidelines re: package versioning

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1470] opened 2024-01-17 17:19 UTC
## QC Details

- Update contributor guidelines with best practices around package versioning.

## Additional Comments

Two use cases:
- Using `{renv}` for package development.
- Using `{renv}`/package versioning for deployed analytics pipelines.
- Related: #1395

**Comment by jwildfire** [comment] 2024-04-03 22:19
I'm still unclear on best practices for using {renv} in package development. Can someone provide an example or link to best practice? 

I think we should leave analytics pipelines out of scope in this package for now. We can consider adding vignettes explaining some of our best practices at a later date. 

cc: @dpastoor @tkwilos @samussiah @mattroumaya

**Comment by jwildfire** [comment] 2024-04-03 22:36
Duplicate of #1395. Please add comments there.

**Closed by jwildfire** 2024-04-03 22:36 UTC
Labels: documentation, devops
