### ISSUE TITLE
QC: Eliminate use of cli_alert_*()

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1678] opened 2024-07-18 14:41 UTC
## QC Details
I finally found [confirmation that `cli_alert_*()` functions are leftovers from an older way of doing things in {cli}](https://github.com/r-lib/devtools/issues/2430). Per that ticket:

- [ ] "cli_alert_danger" = "use cli::cli_inform()" (but I'd guess we probably actually mean `cli_abort()` or `cli_warn()`)
- [ ] "cli_alert_info" = "use cli::cli_inform()"
- [ ] "cli_alert_success" = "use cli::cli_inform()"
- [ ] "cli_alert_warning" = "use cli::cli_inform()" (but I assume we actually mean `cli_warn()`)

The main issue I've found is that `cli_alert_warning()` doesn't actually count as a warning for testing; it's just a message dressed up as a warning. Not a HUGE issue but can make things confusing.

**Comment by jwildfire** [comment] 2024-07-18 19:26
Makes sense to me to tighten this up. Let's address in v2.1 or v2.2. We may also want to do a more through review of our logging as we move more runs in to GHA.

**Comment by lauramaxwell** [comment] 2024-09-04 19:49
Based on discussion in #1814 , we should replace `cli_alert_danger()` with `cli_abort()` in most cases so that we don't continue in a pipeline that has failed validation-type checks.

**Comment by lauramaxwell** [comment] 2024-11-11 20:47
duplicate of #1933

**Closed by lauramaxwell** 2024-11-11 20:47 UTC
Labels: enhancement
