### ISSUE TITLE
Bugfix: Readme images not rendering in gihub

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1308] opened 2023-09-12 15:20 UTC
## Expected Behavior

<img width="523" alt="image" src="https://github.com/Gilead-BioStats/gsm/assets/3680095/5a6ee304-f184-4954-b344-1576789e8eb2">

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mattroumaya** [comment] 2023-09-12 15:22
Duplicate of #1305

**Closed by mattroumaya** 2023-09-12 15:22 UTC
