### ISSUE TITLE
fix bug with converting past stacked snapshots to new data model and preserving longitudinal data

### ISSUE THREAD

**Issue by andersonjake1988** [Gilead-BioStats/gsm#1477] opened 2024-01-25 16:37 UTC
UpdateSnapshotLogs is expecting a list of KRI's (like found in lSnapshot) but instead is getting a list of logs. (study_status etc.) need to augment function to convert and append new data to it

**Comment by mattroumaya** [comment] 2024-03-18 15:08
@andersonjake1988 is this still an issue?

**Comment by mattroumaya** [comment] 2024-04-02 19:09
Closing as duplicate of #1512

**Closed by mattroumaya** 2024-04-02 19:09 UTC
Labels: bug
